USE [master]
GO

/****** Object:  Database [dbOnlineShop]    Script Date: 23/06/2023 22:07:08 ******/
CREATE DATABASE [dbOnlineShop]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'dbOnlineShop', FILENAME = N'D:\UNITBV\MSSQL15.SQLEXPRESS\MSSQL\DATA\dbOnlineShop.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'dbOnlineShop_log', FILENAME = N'D:\UNITBV\MSSQL15.SQLEXPRESS\MSSQL\DATA\dbOnlineShop_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [dbOnlineShop].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [dbOnlineShop] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [dbOnlineShop] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [dbOnlineShop] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [dbOnlineShop] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [dbOnlineShop] SET ARITHABORT OFF 
GO

ALTER DATABASE [dbOnlineShop] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [dbOnlineShop] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [dbOnlineShop] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [dbOnlineShop] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [dbOnlineShop] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [dbOnlineShop] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [dbOnlineShop] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [dbOnlineShop] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [dbOnlineShop] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [dbOnlineShop] SET  DISABLE_BROKER 
GO

ALTER DATABASE [dbOnlineShop] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [dbOnlineShop] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [dbOnlineShop] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [dbOnlineShop] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [dbOnlineShop] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [dbOnlineShop] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [dbOnlineShop] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [dbOnlineShop] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [dbOnlineShop] SET  MULTI_USER 
GO

ALTER DATABASE [dbOnlineShop] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [dbOnlineShop] SET DB_CHAINING OFF 
GO

ALTER DATABASE [dbOnlineShop] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [dbOnlineShop] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [dbOnlineShop] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [dbOnlineShop] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [dbOnlineShop] SET QUERY_STORE = OFF
GO

ALTER DATABASE [dbOnlineShop] SET  READ_WRITE 
GO

